variable "resource_group_name" {
  description = "Resource group for the Flexible Server."
  type        = string
}

variable "region" {
  description = "Azure region. Free-tier B1ms support varies by region; eastus is verified."
  type        = string
}

variable "name_prefix" {
  description = "Resource name prefix, e.g. 'kanto-dev'."
  type        = string
}

variable "name_suffix" {
  description = "Optional suffix on the server name. Used to bypass Azure DNS reservations from a prior failed create attempt."
  type        = string
  default     = ""
}

variable "vnet_integration_enabled" {
  description = "Use a delegated subnet + private DNS zone (private endpoint only). When false, the server exposes a public endpoint guarded by firewall rules (see allowed_cidrs)."
  type        = bool
  default     = true
}

variable "subnet_id" {
  description = "Delegated subnet for VNet-integrated Flexible Server. Required when vnet_integration_enabled = true; ignored otherwise."
  type        = string
  default     = null
  nullable    = true
}

variable "private_dns_zone_id" {
  description = "Private DNS zone the server registers in (postgres.database.azure.com pattern). Required when vnet_integration_enabled = true; ignored otherwise."
  type        = string
  default     = null
  nullable    = true
}

variable "allowed_cidrs" {
  description = "CIDRs allowed through the Postgres firewall when vnet_integration_enabled = false. /32 entries become single-IP rules; broader CIDRs are expanded to first/last host."
  type        = list(string)
  default     = []
}

variable "allow_azure_services" {
  description = "When true (and vnet_integration_enabled = false), adds the AllowAllAzureServices firewall rule so resources in any Azure subscription can reach the server. Auth is still required. Useful when AKS egress IPs are dynamic."
  type        = bool
  default     = false
}

variable "admin_username" {
  description = "Postgres admin user name. Cannot be 'postgres', 'admin', 'root' (reserved)."
  type        = string
  default     = "kanto_admin"
}

variable "admin_password" {
  description = "Initial admin password. Generated by the key_vault module's random_password, then stored as a Key Vault secret. Sensitive."
  type        = string
  sensitive   = true
}

variable "database_name" {
  description = "Logical database created on the server."
  type        = string
  default     = "kanto"
}

variable "postgres_version" {
  description = "Major Postgres version. 16 supports pgvector out of the box."
  type        = string
  default     = "16"
}

variable "sku_name" {
  description = "Flexible Server SKU. 'B_Standard_B1ms' is free for 12 months."
  type        = string
}

variable "storage_gb" {
  description = "Storage in GB. Flexible Server steps at 32, 64, 128, 256, 512, 1024..."
  type        = number
  default     = 32
}

variable "high_availability" {
  description = "Zone-redundant HA. Requires GP tier; ignored on Burstable SKUs."
  type        = bool
  default     = false
}

variable "backup_retention_days" {
  description = "Automatic backup retention. Min 7 / max 35."
  type        = number
  default     = 7
}

variable "tags" {
  description = "Tags applied to every resource."
  type        = map(string)
  default     = {}
}
